package hrms_g1.Gui.Profile_Management;
import Users.HumanResourceOfficer;
import javax.swing.JFrame;

public class Create_User_Account extends javax.swing.JFrame {
    private String username;
    private final JFrame previousWindow;  
    
    public Create_User_Account(JFrame previousWindow, String username) {
        this.previousWindow = previousWindow;
        this.username = username;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        createUserAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        getUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        getName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        getEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        getContact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        getAddress = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        getDepartment = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        getPosition = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        searchUsername = new javax.swing.JButton();
        usernameSearch = new javax.swing.JTextField();
        getEmergencyContact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        getWorkExp = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        getGender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(728, 410));
        setPreferredSize(new java.awt.Dimension(728, 410));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Account");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 10, 127, 44);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(6, 17, 72, 23);

        createUserAccount.setText("Create");
        createUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createUserAccount);
        createUserAccount.setBounds(320, 370, 72, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 110, 60, 15);
        getContentPane().add(getUsername);
        getUsername.setBounds(100, 130, 210, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 160, 50, 15);

        getName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNameActionPerformed(evt);
            }
        });
        getContentPane().add(getName);
        getName.setBounds(100, 180, 210, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 210, 40, 15);
        getContentPane().add(getEmail);
        getEmail.setBounds(100, 230, 210, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Contact :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 260, 50, 15);
        getContentPane().add(getContact);
        getContact.setBounds(100, 280, 210, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Address :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(380, 110, 50, 15);

        getAddress.setColumns(20);
        getAddress.setRows(5);
        jScrollPane1.setViewportView(getAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 130, 234, 86);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Emergency Contact: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 310, 140, 15);

        getDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Department", "Payroll Department", "General Employee" }));
        getContentPane().add(getDepartment);
        getDepartment.setBounds(380, 250, 136, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Position :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(530, 230, 50, 15);

        getPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Officer", "Recruitment", "Specialist", "Clerk", "Intern", "Staff Member", "Trainee", "Junior Employee" }));
        getContentPane().add(getPosition);
        getPosition.setBounds(530, 250, 121, 22);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(100, 50, 530, 10);

        searchUsername.setText("Search");
        searchUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(searchUsername);
        searchUsername.setBounds(360, 70, 72, 23);
        getContentPane().add(usernameSearch);
        usernameSearch.setBounds(260, 70, 80, 22);
        getContentPane().add(getEmergencyContact);
        getEmergencyContact.setBounds(100, 330, 210, 22);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("Department :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 230, 70, 15);
        getContentPane().add(getWorkExp);
        getWorkExp.setBounds(380, 300, 64, 22);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("Gender");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(530, 280, 70, 15);

        getGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(getGender);
        getGender.setBounds(530, 300, 72, 22);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 242, 242));
        jLabel13.setText("Work Exp:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(380, 280, 70, 15);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\images\\profile_management_km.jpg")); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -24, 730, 460);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 290, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserAccountActionPerformed
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String employeeUsername = getUsername.getText();
        String name = getName.getText();
        String contact = getContact.getText();
        String email = getEmail.getText();
        String address = getAddress.getText();
        String position = getPosition.getSelectedItem().toString();
        String department = getDepartment.getSelectedItem().toString();
        String emergencyContact = getEmergencyContact.getText();
        int workExperience = (int) getWorkExp.getValue();
        String gender = getGender.getSelectedItem().toString();

        
        int role = Integer.parseInt(hr.retrieveUserDetails(employeeUsername)[0]); // e.g., role could be a constant or set by the form
        int loginAttempts = 0;
        int accountStatus = Integer.parseInt(hr.retrieveUserDetails(employeeUsername)[4]); // e.g., 1 for active, 0 for inactive
        String monthlyGSalary = "0"; // Example value
        

        HumanResourceOfficer hrOfficer = new HumanResourceOfficer();
        hrOfficer.createEmployeeProfile(role, employeeUsername, hr.retrieveUserDetails(employeeUsername)[2], loginAttempts, accountStatus, name, contact, email, address, emergencyContact, workExperience, position, department, monthlyGSalary, gender);

        javax.swing.JOptionPane.showMessageDialog(this, "User account created successfully!");
        this.dispose();
        previousWindow.setVisible(true); 
    }//GEN-LAST:event_createUserAccountActionPerformed

    private void getNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNameActionPerformed

    private void searchUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUsernameActionPerformed
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String username = usernameSearch.getText();

        String[] userDetails = hr.retrieveUserDetails(username);

        if (userDetails != null) {
            getUsername.setText(userDetails[1]);
            getName.setText(userDetails[5]);
            getContact.setText(userDetails[6]);
            getEmail.setText(userDetails[7]);
            getAddress.setText(userDetails[8]);
            getPosition.setSelectedItem(userDetails[11]); 
            getDepartment.setSelectedItem(userDetails[12]);
            getEmergencyContact.setText(userDetails[9]);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "User not found!");
        }
    }//GEN-LAST:event_searchUsernameActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createUserAccount;
    private javax.swing.JTextArea getAddress;
    private javax.swing.JTextField getContact;
    private javax.swing.JComboBox<String> getDepartment;
    private javax.swing.JTextField getEmail;
    private javax.swing.JTextField getEmergencyContact;
    private javax.swing.JComboBox<String> getGender;
    private javax.swing.JTextField getName;
    private javax.swing.JComboBox<String> getPosition;
    private javax.swing.JTextField getUsername;
    private javax.swing.JSpinner getWorkExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton searchUsername;
    private javax.swing.JTextField usernameSearch;
    // End of variables declaration//GEN-END:variables
}
