/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms_g1.Gui.Profile_Management;
import Users.SystemAdministrator;
import javax.swing.JFrame;

/**
 *
 * @author tvanm
 */
public class Delete_User_Account extends javax.swing.JFrame {
    private String username;
    private final JFrame previousWindow;  
    
    public Delete_User_Account(JFrame previousWindow, String username) {
        this.previousWindow = previousWindow;
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUsername = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchBarUsername = new javax.swing.JTextField();
        searchUsername = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        getName = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        getPosition = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        getDepartment = new javax.swing.JTextPane();
        deleteButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(727, 405));
        setPreferredSize(new java.awt.Dimension(727, 405));
        setResizable(false);
        getContentPane().setLayout(null);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(6, 17, 72, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Delete Account");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 20, 122, 21);

        searchBarUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(searchBarUsername);
        searchBarUsername.setBounds(290, 80, 64, 22);

        searchUsername.setText("Search");
        searchUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(searchUsername);
        searchUsername.setBounds(380, 80, 72, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 120, 38, 15);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Position :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 180, 50, 15);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Department :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 240, 70, 15);

        jScrollPane1.setViewportView(getName);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 140, 153, 22);

        jScrollPane2.setViewportView(getPosition);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(300, 200, 153, 22);

        jScrollPane3.setViewportView(getDepartment);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(300, 260, 153, 22);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(330, 320, 72, 23);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(170, 363, 400, 10);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(180, 50, 370, 10);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\images\\profile_management_km.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-2, -4, 740, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarUsernameActionPerformed

    }//GEN-LAST:event_searchBarUsernameActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        SystemAdministrator admin = new SystemAdministrator();
        admin.deleteUserAccount(setUsername.getText());
        javax.swing.JOptionPane.showMessageDialog(this, "User successfully Deleted!");
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUsernameActionPerformed
        SystemAdministrator admin = new SystemAdministrator();
        String[] userDetails = admin.retrieveUserDetails(searchBarUsername.getText());

        if (userDetails != null && userDetails.length >= 13) {
            getName.setText(userDetails[5]);
            getPosition.setText(userDetails[11]); 
            getDepartment.setText(userDetails[12]);
            setUsername.setText(searchBarUsername.getText());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "User not found or data incomplete!");
        }
    }//GEN-LAST:event_searchUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextPane getDepartment;
    private javax.swing.JTextPane getName;
    private javax.swing.JTextPane getPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField searchBarUsername;
    private javax.swing.JButton searchUsername;
    private javax.swing.JTextField setUsername;
    // End of variables declaration//GEN-END:variables
}
