/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms_g1.Gui.Profile_Management;
import Users.HumanResourceOfficer;
import Users.SystemAdministrator;
import javax.swing.JFrame;

/**
 *
 * @author tvanm
 */
public class Update_Account_Status extends javax.swing.JFrame {
    private String username;
    private final JFrame previousWindow;  
    
    public Update_Account_Status(JFrame previousWindow, String username) {
        this.previousWindow = previousWindow;
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setUsername = new javax.swing.JTextField();
        searchBarUsername = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        getAccountStatus = new javax.swing.JTextPane();
        disableAccount = new javax.swing.JButton();
        enableAccount = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setUsername.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(727, 405));
        setPreferredSize(new java.awt.Dimension(727, 405));
        setResizable(false);
        getContentPane().setLayout(null);

        searchBarUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(searchBarUsername);
        searchBarUsername.setBounds(250, 80, 71, 22);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(6, 17, 72, 23);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(350, 80, 72, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(210, 70, 275, 10);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Account Status :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 130, 86, 15);

        jScrollPane1.setViewportView(getAccountStatus);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 130, 177, 22);

        disableAccount.setText("Disable");
        disableAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableAccountActionPerformed(evt);
            }
        });
        getContentPane().add(disableAccount);
        disableAccount.setBounds(310, 210, 72, 23);

        enableAccount.setText("Enable");
        enableAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableAccountActionPerformed(evt);
            }
        });
        getContentPane().add(enableAccount);
        enableAccount.setBounds(310, 180, 72, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Update Account Status");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 30, 180, 21);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(190, 340, 310, 10);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\images\\profile_management_km.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -4, 730, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBarUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarUsernameActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        SystemAdministrator admin = new SystemAdministrator();
        String[] userDetails = admin.retrieveUserDetails(searchBarUsername.getText());

        if (userDetails != null && userDetails.length >= 13) {
            getAccountStatus.setText(userDetails[4].equals("1")? "Enabled" : "Disabled");
            setUsername.setText(searchBarUsername.getText());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "User not found or data incomplete!");
        }
        if ("1".equals(userDetails[4])) {
            enableAccount.setEnabled(false); 
            disableAccount.setEnabled(true); 
        } else if ("0".equals(userDetails[4])) {
            disableAccount.setEnabled(false); 
            enableAccount.setEnabled(true); 
        } else {
            enableAccount.setEnabled(false);
            disableAccount.setEnabled(false);
        }        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void enableAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableAccountActionPerformed
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String username = searchBarUsername.getText();
        
        String[] userDetails = hr.retrieveUserDetails(username);
        
        userDetails[4] = "1";
                
        hr.updateEmployeeProfile(userDetails);
        javax.swing.JOptionPane.showMessageDialog(this, "Status changed successfully!");
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_enableAccountActionPerformed

    private void disableAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableAccountActionPerformed
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String username = searchBarUsername.getText();
        
        String[] userDetails = hr.retrieveUserDetails(username);
        
        userDetails[4] = "0";
                
        hr.updateEmployeeProfile(userDetails);
        javax.swing.JOptionPane.showMessageDialog(this, "Status changed successfully!");
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_disableAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton disableAccount;
    private javax.swing.JButton enableAccount;
    private javax.swing.JTextPane getAccountStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField searchBarUsername;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField setUsername;
    // End of variables declaration//GEN-END:variables
}
