/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms_g1.Gui.Profile_Management;
import Users.HumanResourceOfficer;
import Users.SystemAdministrator;
import javax.swing.JFrame;

/**
 *
 * @author tvanm
 */
public class Update_Account_Details extends javax.swing.JFrame {
    private String username;
    private final JFrame previousWindow;  
    
    public Update_Account_Details(JFrame previousWindow, String username) {
        this.previousWindow = previousWindow;
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameSearchBar = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        getName = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        getPosition = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        getDepartment = new javax.swing.JComboBox<>();
        getRole = new javax.swing.JComboBox<>();
        changeButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        searchButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(727, 405));
        setPreferredSize(new java.awt.Dimension(727, 405));
        setResizable(false);
        getContentPane().setLayout(null);

        usernameSearchBar.setText("Username");
        usernameSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameSearchBarActionPerformed(evt);
            }
        });
        getContentPane().add(usernameSearchBar);
        usernameSearchBar.setBounds(280, 70, 80, 22);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(6, 17, 72, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 110, 38, 15);

        jScrollPane1.setViewportView(getName);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 130, 170, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Position :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 160, 50, 15);

        getPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Officer", "Recruitment", "Specialist", "Clerk", "Intern", "Staff Member", "Trainee", "Junior Employee" }));
        getContentPane().add(getPosition);
        getPosition.setBounds(280, 180, 170, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Department :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 210, 70, 15);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Role :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 260, 50, 15);

        getDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Department", "Payroll Department", "General Employee", " " }));
        getContentPane().add(getDepartment);
        getDepartment.setBounds(280, 230, 170, 22);

        getRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR Officer", "Department Manager", "Payroll Officer", "General Employee" }));
        getContentPane().add(getRole);
        getRole.setBounds(280, 280, 170, 22);

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changeButton);
        changeButton.setBounds(320, 320, 72, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(190, 60, 335, 10);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Update Account Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 30, 190, 21);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(180, 360, 350, 10);

        searchButton.setText("Search");
        getContentPane().add(searchButton);
        searchButton.setBounds(370, 70, 72, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\images\\profile_management_km.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 730, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameSearchBarActionPerformed
        // TODO add your handling code here:
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String username = usernameSearchBar.getText();

        String[] userDetails = hr.retrieveUserDetails(username);
        
        String[] roles = {"Admin", "HR Officer", "Department Manager", "Payroll Officer", "General Employee"}; 
        
        if (userDetails != null) {
            getName.setText(userDetails[5]);
            getPosition.setSelectedItem(userDetails[11]); 
            getDepartment.setSelectedItem(userDetails[12]);
            getRole.setSelectedItem(roles[Integer.parseInt(userDetails[0])]);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "User not found!");
        }
    }//GEN-LAST:event_usernameSearchBarActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String username = usernameSearchBar.getText();
        
        String[] userDetails = hr.retrieveUserDetails(username);
        userDetails[5] = getName.getText();
        userDetails[11] = getPosition.getSelectedItem().toString();
        userDetails[12] = getDepartment.getSelectedItem().toString();
        int role;
        switch (getRole.getSelectedItem().toString()) {
            case "Admin" -> role = 1;
            case "HR Officer" -> role = 2;
            case "Department Manager" -> role = 3;
            case "Payroll Officer" -> role = 4;
            case "General Employee" -> role = 5;
            default -> {
                role = 5;
                System.out.println("Invalid Department");
                return;
            }
        }
        userDetails[0] = Integer.toString(role);
        
        hr.updateEmployeeProfile(userDetails);
        javax.swing.JOptionPane.showMessageDialog(this, "Details changed successfully!");
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_changeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changeButton;
    private javax.swing.JComboBox<String> getDepartment;
    private javax.swing.JTextPane getName;
    private javax.swing.JComboBox<String> getPosition;
    private javax.swing.JComboBox<String> getRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField usernameSearchBar;
    // End of variables declaration//GEN-END:variables
}
