/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms_g1.Gui.Profile_Management;
import Users.HumanResourceOfficer;
import javax.swing.JFrame;

/**
 *
 * @author tvanm
 */
public class View_Profile extends javax.swing.JFrame {
    private String username;
    private final JFrame previousWindow;  
    
    public View_Profile(JFrame previousWindow, String username) {
        this.previousWindow = previousWindow;
        this.username = username;
        initComponents();
        
        HumanResourceOfficer hr = new HumanResourceOfficer();
        String[] userDetails = hr.retrieveUserDetails(username);

        if (userDetails != null) {
            getUsername.setText(userDetails[1]);
            getName.setText(userDetails[5]);
            getContact.setText(userDetails[6]);
            getEmail.setText(userDetails[7]);
            getAddress.setText(userDetails[8]);
            getPosition.setText(userDetails[11]); 
            getDepartment.setText(userDetails[12]);
            getEmergencyContact.setText(userDetails[9]);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "User not found!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        getUsername = new javax.swing.JTextPane();
        getName = new javax.swing.JTextField();
        getEmail = new javax.swing.JTextField();
        getContact = new javax.swing.JTextField();
        getEmergencyContact = new javax.swing.JTextField();
        getAddress = new javax.swing.JTextField();
        getPosition = new javax.swing.JTextField();
        getDepartment = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(727, 405));
        setPreferredSize(new java.awt.Dimension(727, 405));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 90, 61, 15);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(6, 17, 72, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 140, 38, 15);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Contact :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 240, 48, 15);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Email :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 190, 37, 15);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Emergency Contact :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 190, 110, 15);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Address :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 240, 51, 15);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Position :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 90, 50, 15);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Department :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 140, 70, 15);

        jScrollPane1.setViewportView(getUsername);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 110, 180, 22);

        getName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNameActionPerformed(evt);
            }
        });
        getContentPane().add(getName);
        getName.setBounds(170, 160, 180, 22);

        getEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmailActionPerformed(evt);
            }
        });
        getContentPane().add(getEmail);
        getEmail.setBounds(170, 210, 180, 22);
        getContentPane().add(getContact);
        getContact.setBounds(170, 260, 180, 22);

        getEmergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEmergencyContactActionPerformed(evt);
            }
        });
        getContentPane().add(getEmergencyContact);
        getEmergencyContact.setBounds(390, 210, 180, 22);
        getContentPane().add(getAddress);
        getAddress.setBounds(390, 260, 180, 22);
        getContentPane().add(getPosition);
        getPosition.setBounds(390, 110, 180, 22);
        getContentPane().add(getDepartment);
        getDepartment.setBounds(390, 160, 180, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(170, 60, 400, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(160, 320, 410, 10);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("My Profile");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 30, 90, 21);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\images\\profile_management_km.jpg")); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, -4, 730, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNameActionPerformed

    private void getEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getEmailActionPerformed

    private void getEmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEmergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getEmergencyContactActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        previousWindow.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField getAddress;
    private javax.swing.JTextField getContact;
    private javax.swing.JTextField getDepartment;
    private javax.swing.JTextField getEmail;
    private javax.swing.JTextField getEmergencyContact;
    private javax.swing.JTextField getName;
    private javax.swing.JTextField getPosition;
    private javax.swing.JTextPane getUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
