/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms_g1.Gui.Payroll_management;
import Users.PayrollOfficer;
import Users.SystemAdministrator;
import javax.swing.JFrame;

/**
 *
 * @author tvanm
 */
public class Create_Payroll extends javax.swing.JFrame {
    private String username;
    private final JFrame previousWindow;    
    
    public Create_Payroll(JFrame previousWindow, String username) {
        this.previousWindow = previousWindow;
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        getUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        getGrossSalary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        setSOCSO = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        setEPF = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        setEIS = new javax.swing.JTextPane();
        setAnnualTex = new javax.swing.JScrollPane();
        setAnnualTax = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        setNetSalary = new javax.swing.JTextPane();
        searchUsername = new javax.swing.JButton();
        createPayroll = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        generatePayDetails1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 70, 20));

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 63, -1, -1));

        getUsername.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        getUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(getUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 71, -1));

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel2.setText("Gross Salary :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 103, -1, -1));

        getGrossSalary.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        getContentPane().add(getGrossSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 71, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel3.setText("EPF :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 147, -1, -1));

        jLabel4.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel4.setText("SOCSO :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 181, -1, -1));

        jLabel5.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel5.setText("EIS :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 215, -1, -1));

        jLabel6.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel6.setText("Annual Tax :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 249, -1, -1));

        jLabel7.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        jLabel7.setText("Net Salary :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 283, -1, -1));

        setSOCSO.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(setSOCSO);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 175, -1, -1));

        setEPF.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(setEPF);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 147, -1, -1));

        setEIS.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(setEIS);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 209, -1, -1));

        setAnnualTax.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        setAnnualTex.setViewportView(setAnnualTax);

        getContentPane().add(setAnnualTex, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 243, -1, -1));

        setNetSalary.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jScrollPane5.setViewportView(setNetSalary);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 277, -1, -1));

        searchUsername.setBackground(new java.awt.Color(0, 0, 0));
        searchUsername.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        searchUsername.setForeground(new java.awt.Color(255, 255, 255));
        searchUsername.setText("Search");
        getContentPane().add(searchUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        createPayroll.setBackground(new java.awt.Color(0, 0, 0));
        createPayroll.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        createPayroll.setForeground(new java.awt.Color(255, 255, 255));
        createPayroll.setText("Create");
        createPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPayrollActionPerformed(evt);
            }
        });
        getContentPane().add(createPayroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 317, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 134, 391, 7));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, 30));

        generatePayDetails1.setBackground(new java.awt.Color(0, 0, 0));
        generatePayDetails1.setFont(new java.awt.Font("Constantia", 1, 12)); // NOI18N
        generatePayDetails1.setForeground(new java.awt.Color(255, 255, 255));
        generatePayDetails1.setText("Generate");
        getContentPane().add(generatePayDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 317, -1, -1));

        jLabel8.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jLabel8.setText("Create Payroll");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\images\\veva_background.jpeg")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 450, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPayrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPayrollActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void getUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getUsernameActionPerformed
    }//GEN-LAST:event_getUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Create_Payroll().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPayroll;
    private javax.swing.JButton generatePayDetails1;
    private javax.swing.JTextField getGrossSalary;
    private javax.swing.JTextField getUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton searchUsername;
    private javax.swing.JTextPane setAnnualTax;
    private javax.swing.JScrollPane setAnnualTex;
    private javax.swing.JTextPane setEIS;
    private javax.swing.JTextPane setEPF;
    private javax.swing.JTextPane setNetSalary;
    private javax.swing.JTextPane setSOCSO;
    // End of variables declaration//GEN-END:variables
}
