/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms_g1.Gui.Dep_Manager;
import hrms_g1.Gui.Leave_Management.Apply_Leave;
import hrms_g1.Gui.Leave_Management.Cancel_Leave;
import hrms_g1.Gui.Leave_Management.Check_Leave_Status;
import hrms_g1.Gui.Leave_Management.Leave_Application_List;

/**
 *
 * @author tvanm
 */
public class Leave_Management_Menu extends javax.swing.JFrame {
    String username;
    /**
     * Creates new form Leave_Management
     */
    public Leave_Management_Menu(String username) {
        this.setTitle("Department Manager Leave Management");
        this.username = username;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        applyLeave = new javax.swing.JButton();
        cancelLeave = new javax.swing.JButton();
        checkLeaveStatus = new javax.swing.JButton();
        leaveApplicationList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(730, 410));
        setPreferredSize(new java.awt.Dimension(730, 410));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(6, 6, 72, 23);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Leave Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 170, 21);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(220, 50, 250, 10);

        applyLeave.setBackground(new java.awt.Color(255, 102, 102));
        applyLeave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        applyLeave.setForeground(new java.awt.Color(242, 242, 242));
        applyLeave.setText("Apply Leave");
        applyLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(applyLeave);
        applyLeave.setBounds(100, 80, 170, 140);

        cancelLeave.setBackground(new java.awt.Color(255, 102, 102));
        cancelLeave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelLeave.setForeground(new java.awt.Color(242, 242, 242));
        cancelLeave.setText("Cancel Leave");
        cancelLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(cancelLeave);
        cancelLeave.setBounds(410, 80, 170, 140);

        checkLeaveStatus.setBackground(new java.awt.Color(255, 102, 102));
        checkLeaveStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        checkLeaveStatus.setForeground(new java.awt.Color(242, 242, 242));
        checkLeaveStatus.setText("Check Leave Status");
        checkLeaveStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLeaveStatusActionPerformed(evt);
            }
        });
        getContentPane().add(checkLeaveStatus);
        checkLeaveStatus.setBounds(100, 240, 170, 140);

        leaveApplicationList.setBackground(new java.awt.Color(255, 102, 102));
        leaveApplicationList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        leaveApplicationList.setForeground(new java.awt.Color(242, 242, 242));
        leaveApplicationList.setText("Leave Application List");
        leaveApplicationList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveApplicationListActionPerformed(evt);
            }
        });
        getContentPane().add(leaveApplicationList);
        leaveApplicationList.setBounds(410, 240, 170, 140);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\images\\dep_manager_km.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 730, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLeaveActionPerformed
        new Cancel_Leave(this, username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelLeaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Dep_Manager_Menu mainPage = new Dep_Manager_Menu(username);
        mainPage.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void applyLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyLeaveActionPerformed
        new Apply_Leave(this, username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_applyLeaveActionPerformed

    private void checkLeaveStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLeaveStatusActionPerformed
        new Check_Leave_Status(this, username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkLeaveStatusActionPerformed

    private void leaveApplicationListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveApplicationListActionPerformed
        new Leave_Application_List(this, username).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_leaveApplicationListActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyLeave;
    private javax.swing.JButton cancelLeave;
    private javax.swing.JButton checkLeaveStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton leaveApplicationList;
    // End of variables declaration//GEN-END:variables
}
